POST http://localhost:5000/forum/question
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFuZmFyaW5sb3llQG91dGxvb2suY29tIiwiZXhwIjoxNjA0MTA3MTI0fQ.I7_cbFeKuRnhK1ttjga7EbLH1c3LjgXfTXxkPKnBrGk

{
"title": "Test Question 9",
  "description": "s if get affects it??",
  "tags": [{
     "name": "one"
  },
    {
      "name": "four"
    }]
}

###

POST http://localhost:5000/v1/auth/login
Content-Type: application/json

{
"email": "jonathanfarinloye@outlook.com",
  "password": "TestingMic1!"
}

###

POST http://localhost:5000/v1/account
Content-Type: application/json

{
  "email": "jonathanfarinloye@outlook.com",
  "first_name": "One",
  "last_name": "T",
  "password": "TestingMic1!",
  "user_name": "family man"
}

###

POST http://localhost:5000/v1/forum/question
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmF0aGFuZmFyaW5sb3llQG91dGxvb2suY29tIiwiZXhwIjoxNjA3OTUyNDc3fQ.NBQdJvvblyasDCdZrO81-MbE5RtTw11FziJw63hSG6I

{
  "title": "Testing question five",
  "description": "Trying tagain ohho hard",
  "tags": [{"name": "Two"}, {"name": "five tag"}]
}

###
GET http://localhost:5000/v1/forum/question/all?filter=One Tag

###
GET http://localhost:5000/v1/account/all?filter=one,two,five&search=airtel